language: csharp
install:
  - DNX_VERSION="1.0.0-beta5"
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_USER_HOME=/opt/dnx DNX_BRANCH=$DNX_VERSION sh
  - bash -c "source /opt/dnx/dnvm/dnvm.sh && dnvm install $DNX_VERSION -a default && dnvm alias default | xargs -i ln -s /opt/dnx/runtimes/{} /opt/dnx/runtimes/default"
  - export PATH=$PATH:/opt/dnx/runtimes/default/bin
before_script:
  - chmod u+x build.sh
  - export TRAVIS_BUILD_NUMBER="0.1.0-beta.1.$TRAVIS_BUILD_NUMBER"
  - mono --version
  - dnu --version
script:
  - ./build.sh --buildNumber=$TRAVIS_BUILD_NUMBER --configuration=RELEASE --outputBasePath=./artifacts --pack
